name: Build MRS from iplist (pages, categories, excludes, auto-bootstrap)

on:
  schedule:
    - cron: "15 */6 * * *"   # каждые 6 часов (UTC): быстрый кэшируемый прогон
    - cron: "20 2 * * 0"     # еженедельно вс 02:20 UTC: чистая сборка без кэша
  workflow_dispatch: {}
  push:
    paths:
      - "config/**"
      - "exclude/**"
      - ".github/workflows/build-mrs.yml"

permissions:
  contents: write   # нужно для одноразового автокоммита exclude/
  pages: write
  id-token: write

concurrency:
  group: build-mrs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build (cached)
    if: github.event_name != 'schedule' || github.event.schedule != '20 2 * * 0'
    runs-on: ubuntu-latest
    env:
      MIHOMO_VERSION: v1.19.14
      GOBIN:  ${{ github.workspace }}/.cache/go/bin
      GOPATH: ${{ github.workspace }}/.cache/go
      DOMAIN_WILDCARD: "0"   # "1" → добавит &wildcard=1 к доменным выгрузкам
      SKIP_BOOTSTRAP: "0"    # "1" → не создавать/коммитить exclude-скелет

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- одноразовый автоскелет exclude/ ----------
      - name: Auto-bootstrap excludes (one-time)
        if: env.SKIP_BOOTSTRAP != '1'
        shell: bash
        run: |
          set -Eeuo pipefail
          need_commit=0

          # собрать список категорий из config/
          declare -a CATEGORIES=()
          while IFS= read -r -d '' d; do
            CATEGORIES+=("$(basename "$d")")
          done < <(find config -mindepth 1 -maxdepth 1 -type d -print0 || true)

          # создать exclude/ если отсутствует
          if [[ ! -d exclude ]]; then
            mkdir -p exclude
            need_commit=1
          fi

          # глобальные файлы
          for f in domain.txt ip4.txt ip6.txt; do
            if [[ ! -f "exclude/$f" ]]; then
              : > "exclude/$f"
              echo "# put one item per line; lines starting with # are comments" >> "exclude/$f"
              need_commit=1
            fi
          done

          # по категориям
          for c in "${CATEGORIES[@]}"; do
            mkdir -p "exclude/$c"
            for f in domain.txt ip4.txt ip6.txt; do
              if [[ ! -f "exclude/$c/$f" ]]; then
                : > "exclude/$c/$f"
                echo "# optional per-category excludes for '$c'" >> "exclude/$c/$f"
                need_commit=1
              fi
            done
          done

          if [[ "$need_commit" -eq 1 ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add exclude
